### ISSUE TITLE
DST doesn't seem to work with nose <1.0 after the last changes

### ISSUE THREAD

**Issue by andrejtokarcik** [Almad/django-sane-testing#24]
After the last commit, 43134814754b6b99058d3727424ee5b2e37238c3, running DST-based tests with nose 0.10.4 ends with an error:

```
   File "/home/andrej/tmp/_pkgs/python/djangosanetesting/testrunner.py", line 106, in run_suite
      addplugins=plugins)
TypeError: __init__() got an unexpected keyword argument 'addplugins'
```

After putting nose 1.0 in the PYTHONPATH, the problem gets fixed. However, AFAIK, it's desired to have the DST framework compatible with lower versions of nose, hence the ticket.

**Comment by Almad** [comment]
Raise minimal supported nose version (closed by ae820c77cfa5ef9715600046966b46c81f1ee249)

**Comment by Almad** [comment]
Well, it affects < 0.11. Easy solution (plugins=) is not enough (default plugins are not loaded) and I guess most of the users has no problem upgading.

Thus, minimal supported version is now 0.11+.
